### ISSUE TITLE
Ошибка 404

### ISSUE THREAD

**Issue by vlade11115** [aliev/runestone#9]
https://aliev.me/runestone/index.html браузер ругается на некорректный сертификат, а если добавить исключение, отдаёт 404. Примерно с 17.00 по Киеву, и до сих пор(17.42 по Киеву).

**Comment by vlade11115** [comment]
Скрин настроек браузера.
![2016-02-28 17-39-00 https aliev me runestone index html](https://cloud.githubusercontent.com/assets/14851148/13380121/43595154-de43-11e5-81f5-22383678df14.png)

**Comment by aliev** [comment]
Спасибо! Пришлось изменить основной домен. Скоро учебник будет доступен по адресу https://aliev.github.io/runestone/
